#!/usr/bin/env python3
"""
Optional collector for query results via an approved SERP API provider.

Currently supported:
- SerpAPI (Google engine) via https://serpapi.com/

This script is intentionally conservative:
- Uses an official API endpoint (no direct scraping of Google pages).
- Requires the user to provide an API key via env var SERPAPI_API_KEY or --api-key.

Outputs:
- CSV with flattened results (one row per result)

Limitations:
- "All negative mentions on the internet" is not achievable; this collects top N
  results per query as returned by the provider.
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import os
import time
import urllib.parse
import urllib.request
import urllib.error
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

from env_utils import load_dotenv
from http_utils import ssl_context


SERPAPI_ENDPOINT = "https://serpapi.com/search.json"


def parse_date(s: str) -> dt.date:
    return dt.date.fromisoformat(s)


def _fmt_us_date(d: dt.date) -> str:
    # Google custom date range uses US format in many integrations
    return f"{d.month:02d}/{d.day:02d}/{d.year:04d}"


def build_time_params(start: Optional[dt.date], end: Optional[dt.date]) -> Dict[str, str]:
    """
    - If start/end provided: use a Google custom date range via tbs.
    - Else: use quick date range "past year".
    """
    if start and end:
        return {"tbs": f"cdr:1,cd_min:{_fmt_us_date(start)},cd_max:{_fmt_us_date(end)}"}
    if start or end:
        raise ValueError("Provide both --start and --end, or neither.")
    return {"as_qdr": "y"}  # past year


def serpapi_search(
    *,
    api_key: str,
    q: str,
    num: int,
    hl: str,
    gl: str,
    start: Optional[dt.date],
    end: Optional[dt.date],
) -> Dict:
    params: Dict[str, str] = {
        "engine": "google",
        "q": q,
        "api_key": api_key,
        "num": str(num),
        "hl": hl,
        "gl": gl,
    }
    params.update(build_time_params(start, end))

    url = SERPAPI_ENDPOINT + "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers={"User-Agent": "negative-media-helper/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=60, context=ssl_context()) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
        return json.loads(raw)
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode("utf-8", errors="replace")
        except Exception:
            body = ""
        raise RuntimeError(f"HTTP {e.code} {e.reason}; body={body[:500]}") from e


def read_queries_csv(path: Path) -> Iterable[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            yield row


def flatten_results(
    *,
    client: str,
    client_slug: str,
    category: str,
    lang: str,
    query: str,
    payload: Dict,
) -> List[Dict[str, str]]:
    out: List[Dict[str, str]] = []
    organic = payload.get("organic_results") or []
    for rank, item in enumerate(organic, start=1):
        out.append(
            {
                "client": client,
                "client_slug": client_slug,
                "category": category,
                "lang": lang,
                "query": query,
                "rank": str(rank),
                "title": str(item.get("title") or ""),
                "link": str(item.get("link") or ""),
                "snippet": str(item.get("snippet") or ""),
                "date": str(item.get("date") or item.get("published_date") or ""),
                "source": str(item.get("source") or ""),
            }
        )
    return out


def write_results_csv(rows: List[Dict[str, str]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "client",
        "client_slug",
        "category",
        "lang",
        "query",
        "rank",
        "title",
        "link",
        "snippet",
        "date",
        "source",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for row in rows:
            w.writerow(row)


def main() -> int:
    ap = argparse.ArgumentParser(description="Collect search results for queries via SerpAPI.")
    ap.add_argument("--queries", type=Path, required=True, help="Path to queries_*.csv generated by negative_media.py")
    ap.add_argument("--out", type=Path, default=Path("out"), help="Output directory")
    ap.add_argument("--api-key", default=None, help="SerpAPI key (or set SERPAPI_API_KEY env var)")
    ap.add_argument("--start", type=parse_date, default=None, help="Start date YYYY-MM-DD (optional)")
    ap.add_argument("--end", type=parse_date, default=None, help="End date YYYY-MM-DD (optional)")
    ap.add_argument("--num", type=int, default=10, help="Max organic results per query (provider-dependent)")
    ap.add_argument("--hl", default="ru", help="Google UI language, e.g. ru/en")
    ap.add_argument("--gl", default="ru", help="Google country, e.g. ru/by/us")
    ap.add_argument("--sleep", type=float, default=1.0, help="Delay between API calls (seconds)")
    ap.add_argument(
        "--max-queries",
        type=int,
        default=0,
        help="For dry runs/cost control: process only first N queries (0 = all)",
    )
    ap.add_argument(
        "--langs",
        default="ru,en,any",
        help="Comma-separated langs to include from queries CSV (default: ru,en,any)",
    )
    args = ap.parse_args()

    # Auto-load local .env if present (does not override existing env vars)
    load_dotenv()

    api_key = args.api_key or os.environ.get("SERPAPI_API_KEY")
    if not api_key:
        raise SystemExit("Missing SerpAPI key. Provide --api-key or set SERPAPI_API_KEY.")

    include_langs = {x.strip() for x in args.langs.split(",") if x.strip()}
    stamp = (args.end or dt.date.today()).isoformat()
    out_csv = args.out / f"findings_{stamp}.csv"

    rows_out: List[Dict[str, str]] = []
    processed = 0

    for row in read_queries_csv(args.queries):
        if row.get("lang") not in include_langs:
            continue
        processed += 1
        if args.max_queries and processed > args.max_queries:
            break

        payload = serpapi_search(
            api_key=api_key,
            q=row["query"],
            num=args.num,
            hl=args.hl,
            gl=args.gl,
            start=args.start,
            end=args.end,
        )
        rows_out.extend(
            flatten_results(
                client=row["client"],
                client_slug=row["client_slug"],
                category=row["category"],
                lang=row["lang"],
                query=row["query"],
                payload=payload,
            )
        )
        time.sleep(max(args.sleep, 0.0))

    write_results_csv(rows_out, out_csv)
    print(f"Wrote: {out_csv} ({len(rows_out)} rows from {processed} queries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

